name: Build Application and Make Release

on:
  push:
    tags:
      - "*"

permissions: {}

jobs:
  build_release:
    name: Build Release
    uses: ./.github/workflows/build.yml
    permissions:
      contents: read
      # Required for Azure Trusted Signing
      id-token: write
      # Required for vcpkg binary cache
      packages: write
    with:
      build-type: Release
      environment: Release
    secrets: inherit

  create_release:
    needs: build_release
    permissions:
      contents: write
    runs-on: ubuntu-slim
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          submodules: "true"
          path: "PenguinLauncher-source"
      - name: Download artifacts
        uses: actions/download-artifact@v8
      - name: Grab and store version
        run: |
          tag_name=$(echo ${{ github.ref }} | grep -oE "[^/]+$")
          echo "VERSION=$tag_name" >> $GITHUB_ENV
      - name: Package artifacts properly
        run: |
          mv ${{ github.workspace }}/PenguinLauncher-source PenguinLauncher-${{ env.VERSION }}
          mv PenguinLauncher-Linux-Qt6-Portable*/PenguinLauncher-portable.tar.gz PenguinLauncher-Linux-Qt6-Portable-${{ env.VERSION }}.tar.gz
          mv PenguinLauncher-Linux-aarch64-Qt6-Portable*/PenguinLauncher-portable.tar.gz PenguinLauncher-Linux-aarch64-Qt6-Portable-${{ env.VERSION }}.tar.gz
          mv PenguinLauncher-*.AppImage/PenguinLauncher-*-x86_64.AppImage PenguinLauncher-Linux-x86_64.AppImage
          mv PenguinLauncher-*.AppImage.zsync/PenguinLauncher-*-x86_64.AppImage.zsync PenguinLauncher-Linux-x86_64.AppImage.zsync
          mv PenguinLauncher-*.AppImage/PenguinLauncher-*-aarch64.AppImage PenguinLauncher-Linux-aarch64.AppImage
          mv PenguinLauncher-*.AppImage.zsync/PenguinLauncher-*-aarch64.AppImage.zsync PenguinLauncher-Linux-aarch64.AppImage.zsync
          mv PenguinLauncher-macOS*/PenguinLauncher.zip PenguinLauncher-macOS-${{ env.VERSION }}.zip
          mv PenguinLauncher-macOS*/PenguinLauncher.dmg PenguinLauncher-macOS-${{ env.VERSION }}.dmg

          tar --exclude='.git' -czf PenguinLauncher-${{ env.VERSION }}.tar.gz PenguinLauncher-${{ env.VERSION }}

          for d in PenguinLauncher-Windows-MSVC*; do
            cd "${d}" || continue
            LEGACY="$(echo -n ${d} | grep -o Legacy || true)"
            ARM64="$(echo -n ${d} | grep -o arm64 || true)"
            INST="$(echo -n ${d} | grep -o Setup || true)"
            PORT="$(echo -n ${d} | grep -o Portable || true)"
            NAME="PenguinLauncher-Windows-MSVC"
            test -z "${LEGACY}" || NAME="${NAME}-Legacy"
            test -z "${ARM64}" || NAME="${NAME}-arm64"
            test -z "${PORT}" || NAME="${NAME}-Portable"
            test -z "${INST}" || mv PenguinLauncher-*.exe ../${NAME}-Setup-${{ env.VERSION }}.exe
            test -n "${INST}" || zip -r -9 "../${NAME}-${{ env.VERSION }}.zip" *
            cd ..
          done

          for d in PenguinLauncher-Windows-MinGW-w64*; do
            cd "${d}" || continue
            INST="$(echo -n ${d} | grep -o Setup || true)"
            PORT="$(echo -n ${d} | grep -o Portable || true)"
            NAME="PenguinLauncher-Windows-MinGW-w64"
            test -z "${PORT}" || NAME="${NAME}-Portable"
            test -z "${INST}" || mv PenguinLauncher-*.exe ../${NAME}-Setup-${{ env.VERSION }}.exe
            test -n "${INST}" || zip -r -9 "../${NAME}-${{ env.VERSION }}.zip" *
            cd ..
          done

          for d in PenguinLauncher-Windows-MinGW-arm64*; do
            cd "${d}" || continue
            INST="$(echo -n ${d} | grep -o Setup || true)"
            PORT="$(echo -n ${d} | grep -o Portable || true)"
            NAME="PenguinLauncher-Windows-MinGW-arm64"
            test -z "${PORT}" || NAME="${NAME}-Portable"
            test -z "${INST}" || mv PenguinLauncher-*.exe ../${NAME}-Setup-${{ env.VERSION }}.exe
            test -n "${INST}" || zip -r -9 "../${NAME}-${{ env.VERSION }}.zip" *
            cd ..
          done

      - name: Create release
        id: create_release
        uses: softprops/action-gh-release@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: ${{ github.ref }}
          name: Penguin Launcher ${{ env.VERSION }}
          draft: true
          prerelease: false
          fail_on_unmatched_files: true
          files: |
            PenguinLauncher-Linux-x86_64.AppImage
            PenguinLauncher-Linux-x86_64.AppImage.zsync
            PenguinLauncher-Linux-aarch64.AppImage
            PenguinLauncher-Linux-aarch64.AppImage.zsync
            PenguinLauncher-Linux-Qt6-Portable-${{ env.VERSION }}.tar.gz
            PenguinLauncher-Linux-aarch64-Qt6-Portable-${{ env.VERSION }}.tar.gz
            PenguinLauncher-Windows-MinGW-w64-${{ env.VERSION }}.zip
            PenguinLauncher-Windows-MinGW-w64-Portable-${{ env.VERSION }}.zip
            PenguinLauncher-Windows-MinGW-w64-Setup-${{ env.VERSION }}.exe
            PenguinLauncher-Windows-MinGW-arm64-${{ env.VERSION }}.zip
            PenguinLauncher-Windows-MinGW-arm64-Portable-${{ env.VERSION }}.zip
            PenguinLauncher-Windows-MinGW-arm64-Setup-${{ env.VERSION }}.exe
            PenguinLauncher-Windows-MSVC-arm64-${{ env.VERSION }}.zip
            PenguinLauncher-Windows-MSVC-arm64-Portable-${{ env.VERSION }}.zip
            PenguinLauncher-Windows-MSVC-arm64-Setup-${{ env.VERSION }}.exe
            PenguinLauncher-Windows-MSVC-${{ env.VERSION }}.zip
            PenguinLauncher-Windows-MSVC-Portable-${{ env.VERSION }}.zip
            PenguinLauncher-Windows-MSVC-Setup-${{ env.VERSION }}.exe
            PenguinLauncher-macOS-${{ env.VERSION }}.zip
            PenguinLauncher-macOS-${{ env.VERSION }}.dmg
            PenguinLauncher-${{ env.VERSION }}.tar.gz
